### Consultar pedidos
GET http://localhost:8081/rest/v1/listar HTTP/1.1


### Cadastrar produto
POST http://localhost:8081/rest/v1/cadastrarPedido HTTP/1.1
Content-Type: application/json

{
    "numeroPedido": 700500,
    "nomeProduto": "Teclado redragon k530",
    "quantidade": 2,
    "precoUnitario": 550.0
}

### GraphQL

POST http://localhost:8081/graphql/v1/listar HTTP/1.1

{
  "query": "{ pedidos { id numeroPedido nomeProduto quantidade precoUnitario } }"
}

### 
POST http://localhost:8081/graphql/v1/listar HTTP/1.1

{
  "query": "{ pedidos { numeroPedido nomeProduto } }"
}