version: '3.8'

services:
  api-servico-a:
      build:
        context: ./servicoA
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - ENV=production
        - PORT=8080
  api-servico-b:
    build:
      context: ./servicoB
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENV=production
      - PORT=8081
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"