global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-servico-a'
    static_configs:
      - targets: ['api-servico-a:8080']

  - job_name: 'api-servico-b'
    static_configs:
      - targets: ['api-servico-b:8081']
