# Use a imagem oficial do MariaDB como imagem base
FROM mariadb:latest

# Copie o arquivo de script SQL para o diretório /docker-entrypoint-initdb.d/
# O MariaDB irá executar automaticamente qualquer arquivo .sql neste diretório ao iniciar
COPY ./script.sql /docker-entrypoint-initdb.d/

# Defina as variáveis de ambiente necessárias, se aplicável
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=my_database
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=root

EXPOSE 3306